'use client'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { firebaseConfig } from "@/firebase";
import { FirebaseAppProvider } from 'reactfire';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <FirebaseAppProvider firebaseConfig={firebaseConfig}>
      <html lang="en">
        <body className={`${inter.variable} ${robotoMono.variable}`}>{children}</body>
      </html>
    </FirebaseAppProvider>
  );
}
